name: neom_generator
description: Neom Generator for Open Neom.
version: 1.3.0
homepage: https://github.com/Cyberneom/neom_generator
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  neom_core:
    git:
      url: git@github.com:Cyberneom/neom_core.git
  neom_commons:
    git:
      url: git@github.com:Cyberneom/neom_commons.git
  neom_frequencies:
    git:
      url: git@github.com:Cyberneom/neom_frequencies.git

#  FUTURE EXPERIMENTAL USE:
#  neom_vr:
#    git:
#      url: git@github.com:Cyberneom/neom_vr.git

  sleek_circular_slider: ^2.0.1

  #Audio Processing Experimental
  surround_frequency_generator: ^1.0.0

  #AudioProcessing
  flutter_sound: ^9.28.0
  pitch_detector_dart: ^0.0.7

  #Tonic is a Flutter-compatible Dart package that models components of music theory.
  #Used for Neom Harmony
  #tonic: ^0.2.4

  #Virtual Reality Experimental
  #  flutter_custom_tabs: 2.1.0
  #  vr_player: ^0.2.0
  #  panorama: ^0.4.1
  #  video_360: ^0.0.8
  #  split_view: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
